export const latestReleases = [
  {
    title: "Nobody 2",
    description:
      "Una secuela explosiva donde Hutch Mansell intenta unas vacaciones en paz... hasta que el caos lo encuentra de nuevo.",
    cast: ["Bob Odenkirk", "Sharon Stone", "Colin Hanks"],
    reviews: [
      {
        nombre: "Ana",
        pais: "España",
        calificacion: 8.8,
        mensaje: "Acción sin respiro y buen humor.",
      },
      {
        nombre: "Luis",
        pais: "México",
        calificacion: 8.5,
        mensaje: "Entretenida de principio a fin.",
      },
    ],
    year: 2025,
    lenguajesDisponibles: ["Inglés", "Español"],
    generos: ["Acción", "Comedia"],
    duracion: 120,
    cantidadVistas: "47K",
    poster: "/last_release/poster01.png",
    banner: "/last_release/p-vertical01.png",
    rating: 4,
  },
  {
    title: "Weapons",
    description:
      "Un misterioso horror donde un aula entera desaparece y un niño descubre secretos magicos oscuros.",
    cast: ["Julia Garner", "Josh Brolin", "Benedict Wong"],
    reviews: [
      {
        nombre: "María",
        pais: "Perú",
        calificacion: 7.9,
        mensaje: "Terror psicológico intrigante.",
      },
      {
        nombre: "Pedro",
        pais: "Argentina",
        calificacion: 7.5,
        mensaje: "Muy inquietante, buen ritmo.",
      },
    ],
    year: 2025,
    lenguajesDisponibles: ["Inglés", "Español"],
    generos: ["Horror", "Thriller"],
    duracion: 110,
    cantidadVistas: "25k",
    poster: "/last_release/poster02.png",
    banner: "/last_release/p-vertical02.png",
    rating: 5,
  },
  {
    title: "The Naked Gun",
    description:
      "El regreso del sarcasmo y la torpeza policial con un estilo irreverente y moderno, retomando la clásica saga.",
    cast: ["Liam Neeson", "Pamela Anderson", "Paul Walter Hauser"],
    reviews: [
      {
        nombre: "Clara",
        pais: "Chile",
        calificacion: 8.3,
        mensaje: "Humor clásico que sigue funcionando.",
      },
      {
        nombre: "Ricardo",
        pais: "Colombia",
        calificacion: 8.0,
        mensaje: "Sátira inteligente y divertida.",
      },
    ],
    year: 2025,
    lenguajesDisponibles: ["Inglés", "Español"],
    generos: ["Comedia", "Policial"],
    duracion: 105,
    cantidadVistas: "320k",
    poster: "/last_release/poster03.png",
    banner: "/last_release/p-vertical03.png",
    rating: 4,
  },
  {
    title: "Freakier Friday",
    description:
      "Una gamberra comedia de intercambio de cuerpos... ¡pero entre cuatro personas! Caos garantizado.",
    cast: ["Jamie Lee Curtis", "Lindsay Lohan", "Actor C", "Actor D"],
    reviews: [
      {
        nombre: "Sofía",
        pais: "Venezuela",
        calificacion: 7.8,
        mensaje: "Divertida y nostálgica.",
      },
      {
        nombre: "Andrés",
        pais: "Uruguay",
        calificacion: 7.6,
        mensaje: "Ligera y entretenida.",
      },
    ],
    year: 2025,
    lenguajesDisponibles: ["Inglés", "Español"],
    generos: ["Comedia", "Fantasía"],
    duracion: 100,
    cantidadVistas: "28K",
    poster: "/last_release/poster04.png",
    banner: "/last_release/p-vertical04.png",
    rating: 3,
  },
  {
    title: "The Conjuring: Last Rites",
    description:
      "La continuación final de la saga, con posesiones y exorcismos que desafían todo lo visto.",
    cast: ["Actriz A", "Actor B"],
    reviews: [
      {
        nombre: "Ana",
        pais: "España",
        calificacion: 8.2,
        mensaje: "Terror intenso hasta el último minuto.",
      },
      {
        nombre: "Carlos",
        pais: "Chile",
        calificacion: 8.0,
        mensaje: "Escalofríos asegurados.",
      },
    ],
    year: 2025,
    lenguajesDisponibles: ["Inglés", "Español"],
    generos: ["Horror", "Suspenso"],
    duracion: 115,
    cantidadVistas: "26k",
    poster: "/last_release/poster05.png",
    banner: "/last_release/p-vertical05.png",
    rating: 3,
  },
  {
    title: "The Black Phone 2",
    description:
      "Un thriller sobrenatural donde un teléfono sirve de nexo con las voces del más allá... de nuevo.",
    cast: ["Actor X", "Actriz Y"],
    reviews: [
      {
        nombre: "Lucía",
        pais: "México",
        calificacion: 7.9,
        mensaje: "Intriga y tensión bien logradas.",
      },
      {
        nombre: "Miguel",
        pais: "Colombia",
        calificacion: 7.7,
        mensaje: "Buen terror moderno.",
      },
    ],
    year: 2025,
    lenguajesDisponibles: ["Inglés", "Español"],
    generos: ["Horror", "Thriller"],
    duracion: 110,
    cantidadVistas: "24k",
    poster: "/last_release/poster06.png",
    banner: "/last_release/p-vertical06.png",
    rating: 4,
  },
  {
    title: "TRON: Ares",
    description:
      "Regreso al mundo digital, donde la inteligencia artificial se enfrenta al sistema en una guerra de código y luz.",
    cast: ["Actor Tron", "Actriz Tron"],
    reviews: [
      {
        nombre: "Mariana",
        pais: "Argentina",
        calificacion: 8.0,
        mensaje: "Visualmente espectacular.",
      },
      {
        nombre: "Diego",
        pais: "Perú",
        calificacion: 7.8,
        mensaje: "Estética retro futurista maravillosa.",
      },
    ],
    year: 2025,
    lenguajesDisponibles: ["Inglés", "Español", "Francés"],
    generos: ["Ciencia ficción", "Acción"],
    duracion: 120,
    cantidadVistas: "30k",
    poster: "/last_release/poster07.png",
    banner: "/last_release/p-vertical07.png",
    rating: 3,
  },
  {
    title: "Avatar: Fire and Ash",
    description:
      "Una nueva aventura en Pandora, explorando tierras volcánicas y antiguas rivalidades entre clanes.",
    cast: ["Actor A", "Actriz B"],
    reviews: [
      {
        nombre: "Valentina",
        pais: "Uruguay",
        calificacion: 8.5,
        mensaje: "Visualmente deslumbrante.",
      },
      {
        nombre: "Tomás",
        pais: "Bolivia",
        calificacion: 8.3,
        mensaje: "El universo Avatar sigue impactando.",
      },
    ],
    year: 2025,
    lenguajesDisponibles: ["Inglés", "Español"],
    generos: ["Aventura", "Fantasía", "Ciencia ficción"],
    duracion: 135,
    cantidadVistas: "40k",
    poster: "/last_release/poster08.png",
    banner: "/last_release/p-vertical08.png",
    rating: 3,
  },
];
