export const mostWatched = [
  {
    title: "Ne Zha 2",
    description:
      "Animación china récord, una aventura mágica que rompió box office a nivel global.",
    cast: [
      "Crystal Lee",
      "Griffin Puatu",
      "Aleks Le",
      "Michelle Yeoh",
      "Vincent Rodriguez III",
      "Rick Zeiff",
      "William Utay",
      "Christopher Swindle",
    ],
    reviews: [
      {
        nombre: "Xia",
        pais: "China",
        calificacion: 5,
        mensaje: "Espectacular y emotiva.",
      },
      {
        nombre: "Hiro",
        pais: "Japón",
        calificacion: 4,
        mensaje: "Animación impecable y conmovedora.",
      },
    ],
    year: 2025,
    lenguajesDisponibles: ["Mandarín", "Inglés", "Español"],
    generos: ["Animación", "Fantasia", "Aventura"],
    duracion: 110,
    cantidadVistas: "190k",
    poster: "/most_watched/poster01.png",
    banner: "/most_watched/vertical01.png",
    rating: 4,
  },
  {
    title: "Lilo & Stitch (2025)",
    description:
      "Remake live-action que revivió el viaje de Lilo y Stitch con corazón y humor.",
    cast: [
      "Maia Kealoha",
      "Chris Sanders",
      "Sydney Agudong",
      "Zach Galifianakis",
      "Billy Magnussen",
      "Amy Hill",
      "Kaipo Dudoit",
      "Tia Carrere",
    ],
    reviews: [
      {
        nombre: "Ana",
        pais: "España",
        calificacion: 4.5,
        mensaje: "Tierna y nostálgica.",
      },
      {
        nombre: "Sofía",
        pais: "México",
        calificacion: 4.5,
        mensaje: "Muy fiel al espíritu original.",
      },
    ],
    year: 2025,
    lenguajesDisponibles: ["Inglés", "Español"],
    generos: ["Aventura", "Comedia", "Familia"],
    duracion: 115,
    cantidadVistas: "102k",
    poster: "/most_watched/poster02.png",
    banner: "/most_watched/vertical02.png",
    rating: 5,
  },
  {
    title: "A Minecraft Movie",
    description:
      "Película basada en el famoso juego, que exploró mundos pixelados con gran fidelidad.",
    cast: [
      "Jason Momoa",
      "Jack Black",
      "Sebastian Hansen",
      "Emma Myers",
      "Danielle Brooks",
      "Jennifer Coolidge",
      "Kate McKinnon",
      "Jemaine Clement",
    ],
    reviews: [
      {
        nombre: "Carlos",
        pais: "México",
        calificacion: 4.5,
        mensaje: "Divertida y visualmente fiel.",
      },
      {
        nombre: "Elena",
        pais: "Colombia",
        calificacion: 3.5,
        mensaje: "Perfecta para fans de Minecraft.",
      },
    ],
    year: 2025,
    lenguajesDisponibles: ["Inglés", "Español", "Portugués"],
    generos: ["Animación", "Aventura", "Familiar"],
    duracion: 105,
    cantidadVistas: "95k",
    poster: "/most_watched/poster03.png",
    banner: "/most_watched/vertical03.png",
    rating: 3,
  },
  {
    title: "Jurassic World Rebirth",
    description:
      "La cuarta entrega de la saga, con dinosaurios y ciencia en una lucha por salvar especies.",
    cast: [
      "Scarlett Johansson",
      "Mahershala Ali",
      "Jonathan Bailey",
      "Rupert Friend",
      "Manuel Garcia-Rulfo",
      "Ed Skrein",
      "Luna Blaise",
      "David Iacono",
    ],
    reviews: [
      {
        nombre: "Lucía",
        pais: "Perú",
        calificacion: 3.5,
        mensaje: "Entretenida y visualmente impresionante.",
      },
      {
        nombre: "Javier",
        pais: "Argentina",
        calificacion: 8.4,
        mensaje: "Una gran mezcla de acción y nostalgia.",
      },
    ],
    year: 2025,
    lenguajesDisponibles: ["Inglés", "Español"],
    generos: ["Acción", "Ciencia ficción", "Aventura"],
    duracion: 133,
    cantidadVistas: "96k",
    poster: "/most_watched/poster04.png",
    banner: "/most_watched/vertical04.png",
    rating: 4,
  },
  {
    title: "Mission: Impossible – The Final Reckoning",
    description:
      "Ethan Hunt en su última misión que rompió récords de taquilla y adrenalina pura.",
    cast: [
      "Tom Cruise",
      "Hayley Atwell",
      "Ving Rhames",
      "Simon Pegg",
      "Esai Morales",
      "Pom Klementieff",
      "Henry Czerny",
      "Angela Bassett",
    ],
    reviews: [
      {
        nombre: "Ana",
        pais: "Argentina",
        calificacion: 5,
        mensaje: "Espectacular de principio a fin.",
      },
      {
        nombre: "Mateo",
        pais: "Uruguay",
        calificacion: 4.5,
        mensaje: "Un cierre perfecto para la saga.",
      },
    ],
    year: 2025,
    lenguajesDisponibles: ["Inglés", "Español"],
    generos: ["Acción", "Thriller"],
    duracion: 145,
    cantidadVistas: "56k",
    poster: "/most_watched/poster05.png",
    banner: "/most_watched/vertical05.png",
    rating: 4,
  },
  {
    title: "Superman (2025)",
    description:
      "Reinicio heroico del mítico Hombre de Acero, explorando su origen y destino.",
    cast: [
      "David Corenswet",
      "Rachel Brosnahan",
      "Nicholas Hoult",
      "Edi Gathegi",
      "Anthony Carrigan",
      "Nathan Fillion",
      "Isabela Merced",
      "Alan Tudyk",
    ],
    reviews: [
      {
        nombre: "María",
        pais: "México",
        calificacion: 5,
        mensaje: "Imponente y emocionante.",
      },
      {
        nombre: "Luis",
        pais: "España",
        calificacion: 3.5,
        mensaje: "Gran inicio para una nueva saga.",
      },
    ],
    year: 2025,
    lenguajesDisponibles: ["Inglés", "Español"],
    generos: ["Acción", "Ciencia ficción", "Aventura"],
    duracion: 130,
    cantidadVistas: "87k",
    poster: "/most_watched/poster06.png",
    banner: "/most_watched/vertical06.png",
    rating: 4,
  },
  {
    title: "F1",
    description:
      "Drama de alta velocidad ambientado en el mundo de la Fórmula 1, con Brad Pitt al volante.",
    cast: [
      "Brad Pitt",
      "Damson Idris",
      "Javier Bardem",
      "Kerry Condon",
      "Tobias Menzies",
      "Kim Bodnia",
      "Shea Whigham",
      "Lewis Hamilton",
    ],
    reviews: [
      {
        nombre: "Diego",
        pais: "Uruguay",
        calificacion: 4,
        mensaje: "Intenso y visualmente impactante.",
      },
      {
        nombre: "Renata",
        pais: "Brasil",
        calificacion: 3.5,
        mensaje: "Una experiencia vibrante en la pista.",
      },
    ],
    year: 2025,
    lenguajesDisponibles: ["Inglés", "Español"],
    generos: ["Drama", "Deportes", "Acción"],
    duracion: 125,
    cantidadVistas: "87k",
    poster: "/most_watched/poster07.png",
    banner: "/most_watched/vertical07.png",
  },
  {
    title: "Intensamente 2",
    description:
      "Secuela de la exitosa película de Pixar, que nos lleva de nuevo a la mente de Riley, ahora adolescente, mientras aparecen nuevas emociones que complican su vida.",
    cast: [
      "Amy Poehler",
      "Maya Hawke",
      "Phyllis Smith",
      "Lewis Black",
      "Tony Hale",
      "Ayo Edebiri",
      "Adèle Exarchopoulos",
      "Diane Lane"
    ],
    reviews: [
      {
        nombre: "Valentina",
        pais: "México",
        calificacion: 5,
        mensaje:
          "Hermosa secuela, toca temas de la adolescencia con mucha sensibilidad.",
      },
      {
        nombre: "Martín",
        pais: "Argentina",
        calificacion: 4,
        mensaje: "Divertida y conmovedora, mantiene el espíritu de la primera.",
      },
    ],
    year: 2024,
    lenguajesDisponibles: ["Inglés", "Español", "Francés"],
    generos: ["Animación", "Aventura", "Comedia", "Familiar"],
    duracion: 96,
    cantidadVistas: "1.3M",
    poster: "/most_watched/poster08.png",
    banner: "/most_watched/vertical08.png",
    rating: 3,
  },
];
